### ISSUE TITLE
Does the database also contains the country? 

### ISSUE THREAD

**Issue by ctschach** [jannikmi/timezonefinder#178] opened 2023-01-28 06:56 UTC
Does the included database also contains the country for the given coordinates?

if so, it would be a great addition to get a „lat, lng to country“ function.

I know, there are other libraries out there, but why should you use multiple databases for similar things?!

**Comment by jannikmi** [comment] 2023-01-28 09:32
Thanks for this feature request. This is a duplicate of #126.
Unfortunately, the underlying data does not include the country names. 

I found that the functionality is provided by the package [reverse-geocoder](https://github.com/thampiman/reverse-geocoder).

Feel free to reopen this issue if you have any additional ideas/questions.

**Closed by jannikmi** 2023-01-28 09:32 UTC
